version: '3.9'

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: pd_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: explorex
      POSTGRES_USER: ex_user
      POSTGRES_PASSWORD: ex_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/db/init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./backend/src/db/seed.sql:/docker-entrypoint-initdb.d/02_seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ex_user -d explorex"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: pd_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  redis_data:
